version: 1
builder:
  configs:
  - platform: ios
    scheme: swift-xml-parser
  - platform: tvos
    scheme: swift-xml-parser
  - platform: watchos
    scheme: swift-xml-parser
  - documentation_targets: [XMLParser]
